### ISSUE TITLE
Run on Remote server

### ISSUE THREAD

**Issue by pixicommerce-old** [RohanDebroy/heroku-buildpack-wkhtmltopdf#2]
i have installed wkhtmltopdf successfully and attached a domain to it how I can generate pdf from another server to heroku app ?

**Comment by RohanDebroy** [comment]
The possible solution is you will have to expose an API from the server that contains the wkhtmltopdf binary. After that, you can communicate with the API to send the information needed by the binary to create pdfs for you.

FYI I will be closing this issue.

P.S I hope I understood your question and I was able to answer it.
