### ISSUE TITLE
Update Heroku Element Readme.md

### ISSUE THREAD

**Issue by markaharper** [RohanDebroy/heroku-buildpack-wkhtmltopdf#4]
Thank you for this buildpack. It works great with wicked_pdf when other buildpacks failed!

Your Heroku Elements Readme.md page does not include the "Changelog v3" description indicating this buildpack works with heroku-22, so I almost skipped testing it. 

Please update your Heroku Elements Readme.md page if possible, helping others select your buildpack over the other non-working buildpacks.

Also, your GitHub "About" reading for this buildpack states "...and works on heroku-20 and heroku-18 stacks." could also be updated to include heroku-22.

Thanks again!

**Comment by RohanDebroy** [comment]
Thank you for your feedback and kind words! I am glad to hear that the buildpack worked well for you with wicked_pdf.

I was not aware of the Heroku elements page. I must have forgotten. And I don't know how to edit it. If you know how to change it you can contact me. Apart from that the GitHub Readme and About sections have been updated.

Thanks for bringing this to my attention, and I really appreciate your support for this buildpack. I built it for the exact same reason and this is the very last version of this buildpack I have added a feature to bypass stack detection. So I hope it will work in the near future.

If you have any other questions or concerns, please don't hesitate to contact me.
